controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - arm_base_joint
      - arm_shoulder_joint
      - arm_elbow_joint
      - arm_wrist_joint
    interface_name: position